// <auto-generated />
namespace TradersPortal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _2104Validation1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2104Validation1));
        
        string IMigrationMetadata.Id
        {
            get { return "202004211752437_21/04Validation1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
